[tools]
"pre-commit" = "4.3.0"
"go" = "1.25"
"go:github.com/ethereum/go-ethereum/cmd/abigen" = "1.16.4"
"go:go.uber.org/mock/mockgen" = "0.6.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"golangci-lint" = "2"
"ubi:incu6us/goimports-reviser" = "3.10.0"
"ubi:mvdan/gofumpt" = "0.9.2"
"ubi:securego/gosec" = "2"
uv = "0.9.5"
